### PR TITLE
Upgrade extension

### LINKED ISSUE #3: How to Use and Examples
Is there any documentation on how to use this ExternBib MediaWiki extension?
Are other extensions required?
I would like to see an example of this extension before trying it. Can you provide a link to an example MediaWiki that uses this extension for cite? The example that I have seen will not allow me to view source of the MediaWIki page.

This extension looks like something I could use,  
Thanks for publishing and providing support for this extension.

### PR DESCRIPTION
**Pull request by jngrad**
Description of changes:
- make search engine diacritics-insensitive
- add Readme file with detailed examples (fixes #3)
- add support for common LaTeX macros, such as those from `textcomp`
- add support for equations, either through MathJax or via basic HTML formatting
- add unit tests, improve code modularity and separation of concerns
- fix various bugs: ambiguous library import paths, user input parsing, broken HTML lists
- improve support for diacritic escape sequences (most Latin scripts are now working)
- use the BibLaTeX specification to format entries
- remove the massive BibTeX file

### CODE REVIEW

**Comment by jngrad** [comment]
The code in this PR has been used in production at our institute for several months now.

* diacritics-insensitive search: queries [author=Häußler](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=author%3DH%C3%A4u%C3%9Fler&databases=icp) and [author=Haussler](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=author%3DHaussler&databases=icp) both return the same results
* `$\mathcal$`, `$\mathscr$`, `$\mathfrak$`, `$\mathbb$` are replaced by the corresponding unicode symbol ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dgeyer09a&databases=icp))
* `Li\textsuperscript{+}` becomes Li<sup>+</sup> ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dsoetens98a&databases=icp))
* `CO\textsubscript{2}` becomes CO<sub>2</sub> ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dli12c&databases=icp))
* `PF$_6$` becomes PF<sub>6</sub> ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dbhargava07a&databases=icp))
* `Na$^+$` becomes Na<sup>+</sup> ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dwohlfarth12a&databases=icp))
* `$^\circ$` becomes the degree symbol ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dgillen72a&databases=icp))
* `$\zeta$` becomes the Greek letter zeta ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dmaiti08a&databases=icp)), also alternatives like `$\upzeta$` (upright version, [example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dehlers18a&databases=icp)) and `$\varphi$` (stylized version) are supported
* `$\leq$` becomes less-or-equal symbol, other inequality symbols are supported  ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dclementi74a&databases=icp))
* formatting like small caps `\textsc{Quantum}` ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dgiannozzi09a&databases=icp)) or  teletype`\texttt{CP2K}` ([example](https://www2.icp.uni-stuttgart.de/~icp/Special:ExternBibSearch?query=cite%3Dhutter08a&databases=icp)) is supported

**Comment by olenz** [comment]
Thank you very much for the contribution. As you may have noticed, I am not really working on this extension anymore, so I find it hard to review your changes. I do not even have a setup anymore to test the changes.
I will merge the pull request, but maybe you can consider to simply take over the management of the repository?

**Comment by jngrad** [comment]
You're welcome! Feel free to give me write rights, this way I could manage PRs and tickets with @mkuron.

I'm not sure I'll be able to commit to the role of maintainer, though. The University of Stuttgart now uses [PUMA](https://puma.ub.uni-stuttgart.de/?lang=en) to manage bibliographies, which has an API to query papers. We are already experimenting with it on the [institute website](https://www.icp.uni-stuttgart.de/icp-publications/), and there are ongoing discussions at the ICP about whether we should use PUMA instead of ExternBib in the future. So even if I could commit to the role of maintainer, if a decision is made to no longer use ExternBib, I would find myself without an infrastructure to test new developments in this extension too.

**Comment by olenz** [comment]
I was not aware that you are at ICP. So we do not actually have new users, which means that if you are not using it anymore, the project is dead anyway.

**Pull request merged**
